# Create a backend service to start the server in port 8000
services:
  backend-service:
    image: 'weather_request'
    build: .
    environment:
      - open_weather_api_key=$open_weather_api_key
    ports:
      - "8000:8000"